### ISSUE TITLE
Address is misleading

### ISSUE THREAD

**Issue by PhilippJust** [wilhelmstinkts/webapp#14]
* People tend to think they might have to enter their address of residence instead of the location where it stinks
* [x] We need to be clearer here ;)

**Comment by pixelbaker** [comment]
I never replied to your email. You are right, I really was expecting that my home address being added when using auto-fill. Also, because when i was testing the feature i was at home at that moment 😊 
But you are absolutely right we need to make sure that the user is aware that the address where he currently smells the odour 😊 
A headline saying something like, "Wo riechst du den Gestank", might do the trick.
